name: pool_vkursi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  excel: ^4.0.2
  http: ^1.2.1
  pool: ^1.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
